# Generated by Django 5.1.5 on 2026-04-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaketLatihan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket', models.CharField(max_length=10)),
                ('nama_program', models.CharField(max_length=100)),
                ('fokus_keamanan', models.TextField()),
                ('rekomendasi_gerakan', models.TextField()),
                ('larangan', models.TextField()),
                ('catatan', models.TextField()),
                ('frekuensi_minggu', models.CharField(blank=True, max_length=50, null=True)),
                ('durasi_sesi', models.CharField(blank=True, max_length=50, null=True)),
                ('set_rep', models.TextField(blank=True, null=True)),
                ('istirahat', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleIntensitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=10)),
                ('kondisi_tubuh', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('intensitas_awal', models.CharField(max_length=50)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleKondisiTubuh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=10)),
                ('bmi_min', models.FloatField()),
                ('bmi_max', models.FloatField()),
                ('kondisi_tubuh', models.CharField(max_length=50)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=10)),
                ('pengalaman', models.CharField(max_length=50)),
                ('teknik_dasar', models.CharField(max_length=50)),
                ('frekuensi_sebelumnya', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RulePenyesuaian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=10)),
                ('tujuan', models.CharField(max_length=50)),
                ('tempat', models.CharField(max_length=50)),
                ('hari', models.CharField(max_length=50)),
                ('waktu', models.CharField(max_length=50)),
                ('penyesuaian', models.CharField(max_length=100)),
                ('split', models.CharField(max_length=100)),
                ('mode_latihan', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleRekomendasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=10)),
                ('batasan_gerakan', models.CharField(max_length=100)),
                ('intensitas_awal', models.CharField(max_length=50)),
                ('penyesuaian', models.CharField(max_length=100)),
                ('paket', models.CharField(max_length=10)),
                ('intensitas_final', models.CharField(max_length=50)),
                ('alasan_rule', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RuleSafety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=10)),
                ('riwayat_cedera', models.CharField(max_length=50)),
                ('batasan_gerakan', models.TextField()),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
