# Generated by Django 5.1.5 on 2026-04-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketlatihan',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paketlatihan',
            name='durasi_sesi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paketlatihan',
            name='fokus_keamanan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paketlatihan',
            name='frekuensi_minggu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paketlatihan',
            name='istirahat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paketlatihan',
            name='larangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paketlatihan',
            name='nama_program',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='paketlatihan',
            name='paket',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paketlatihan',
            name='rekomendasi_gerakan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruleintensitas',
            name='rule_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rulekondisitubuh',
            name='rule_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rulelevel',
            name='rule_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rulepenyesuaian',
            name='mode_latihan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rulepenyesuaian',
            name='rule_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rulepenyesuaian',
            name='split',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rulerekomendasi',
            name='alasan_rule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rulerekomendasi',
            name='paket',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rulerekomendasi',
            name='rule_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rulesafety',
            name='batasan_gerakan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rulesafety',
            name='rule_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
