# Generated by Django 5.1.5 on 2026-06-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_paketlatihan_catatan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulePenyesuaianAlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=20, unique=True)),
                ('tempat', models.CharField(max_length=50)),
                ('equip_home', models.CharField(max_length=50)),
                ('label_equip_home', models.CharField(blank=True, max_length=100, null=True)),
                ('hari', models.CharField(max_length=50)),
                ('rekomendasi_gerakan', models.TextField()),
                ('catatan_alat', models.TextField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
